#!/bin/bash

/usr/sbin/useradd -r -s /sbin/nologin command
mkdir -p ./.build/command/
cd ./.build/command/
cp -r ../../containers/22-command/app ./
cat > Dockerfile <<'EOF'
FROM debian
RUN apt update -y
RUN apt install -y python3.7
RUN apt install -y python3-pip
RUN pip3 install aiohttp 
RUN pip3 install requests
RUN pip3 install stanfordnlp
RUN python3 -c 'import standfordnlp; standfordnlp.download("en")'
RUN pip3 install SpeechRecognition
COPY ./app /opt/app
CMD ["python3", "/opt/app"]
EOF
docker build -t command .
cd ../../
rm -rf ./.build/command/
