#!/bin/bash

/usr/sbin/useradd -r -s /sbin/nologin command
mkdir -p ./.build/command/
cd ./.build/command/
cp -r ../../containers/22-command/app ./
cat > Dockerfile <<'EOF'
FROM debian
RUN apt update -y && apt upgrade -y && \
  apt install -y python3.7 \
    python3-pip \
    python3-all-dev \
    build-essential \
    swig \
    git \
    libpulse-dev \
    libasound2-dev
RUN apt install -y curl
RUN pip3 install pocketsphinx \
  SpeechRecognition \
  aiohttp \
  requests \
  stanfordnlp \
  python-openhab \
  flask
RUN python3 -c 'import stanfordnlp; stanfordnlp.download("en",force=True)'
RUN apt install -y wget screen
RUN wget https://www.signalogic.com/melp/EngSamples/Orig/male.wav
COPY ./app /opt/app
EOF
docker build -t command .
cd ../../
rm -rf ./.build/command/
