#!/bin/bash

$(basic_container dnsmasq) \
  --cap-add=NET_ADMIN \
  -v 'dnsmasq:/etc/dnsmasq/' \
  -p 53:53 \
  -p 67:67/udp \
  dnsmasq
public_service dns
docker start dnsmasq
docker exec -it dnsmasq \
  sed -i "/${HOST_GATEWAY}/ d" /etc/resolv.conf
docker stop dnsmasq

