#!/bin/bash
source ./bin/activate

$(basic_container openhab) \
  --net=openhab \
  --env CRYPTO_POLICY='limited' \
  --env EXTRA_JAVA_OPTS='-Dhttp.proxySet=true -Dhttp.proxyHost=squid -Dhttp.proxyPort=3128 -Dhttps.proxyHost=squid -Dhttps.proxyPort=3128 -Dhttp.nonProxyHosts=localhost -Dhttp.socksProxyHost=squid -Dhttp.socksProxyPort=3128' \
  --env HTTP_PROXY='http://squid:3128' \
  --env HTTPS_PROXY='http://squid:3128' \
  --env http_proxy='http://squid:3128' \
  --env https_proxy='http://squid:3128' \
  $(container_use_system_time) \
  -v 'openhab_conf:/openhab/conf/' \
  -v 'openhab_userdata:/openhab/userdata/' \
  -v 'openhab_addons:/openhab/addons/' \
  openhab/openhab
set_volume_ownership openhab openhab_conf
set_volume_ownership openhab openhab_userdata
set_volume_ownership openhab openhab_addons
http_egress openhab
http_ingress openhab
docker start openhab
