#!/bin/bash
source ./bin/activate

docker pull openhab/openhab
docker volume create openhab_conf
docker volume create openhab_userdata
docker volume create openhab_addons
docker network create openhab --internal
docker run -d \
  --env USER_ID=$(grep -P '^openhab' /etc/passwd | awk -F':' '{print $3}') \
  --env GROUP_ID=$(grep -P '^openhab' /etc/group | awk -F':' '{print $3}') \
  --restart=always \
  --name=openhab \
  --net=host \
  --env CRYPTO_POLICY='limited' \
  $(container_use_system_time) \
  -v 'openhab_conf:/openhab/conf/' \
  -v 'openhab_userdata:/openhab/userdata/' \
  -v 'openhab_addons:/openhab/addons/' \
  openhab/openhab
sleep 15
docker stop openhab
docker rm openhab

cat >> ${VOLUMES}/openhab_conf/_data/services/addons.cfg <<'EOF'
persistence = 'jdbc'
EOF

touch ${VOLUMES}/openhab_userdata/_data/sqlite.db
cat > ${VOLUMES}/openhab_conf/_data/services/jdbc.cfg <<'EOF'
url=jdbc:sqlite:/openhab/userdata/sqlite.db
EOF

set_volume_ownership openhab openhab_conf
set_volume_ownership openhab openhab_userdata
set_volume_ownership openhab openhab_addons
