#!/bin/bash

docker stop squid
docker rm squid
docker create \
  --env USER_ID=$(grep -P '^squid' /etc/passwd | awk -F':' '{print $3}') \
  --env GROUP_ID=$(grep -P '^squid' /etc/group | awk -F':' '{print $3}') \
  --restart=always \
  --name=squid \
  -v '/etc/localtime:/etc/localtime:ro' \
  -v '/etc/timezone:/etc/timezone:ro' \
  -v 'squid_spool:/var/spool/squid' \
  -v 'squid_conf:/etc/squid/' \
  -p 80:80 \
  -p 443:443 \
  sameersbn/squid
docker start squid
