#!/bin/bash

docker create \
  $(run_as squid) \
  --restart=always \
  --name=squid \
  --net=egress \
  -v '/etc/localtime:/etc/localtime:ro' \
  -v '/etc/timezone:/etc/timezone:ro' \
  -v 'squid_spool:/var/spool/squid' \
  -v 'squid_conf:/etc/squid/' \
  squid
docker start squid
