#!/bin/bash

docker run -d \
  --env USER_ID=$(grep -P '^dnsmasq' /etc/passwd | awk -F':' '{print $3}') \
  --env GROUP_ID=$(grep -P '^dnsmasq' /etc/group | awk -F':' '{print $3}') \
  --restart=always \
  --name=dnsmasq \
  --net=dnsmasq \
  --ip=172.22.0.2 \
  --cap-add=NET_ADMIN \
  -v 'dnsmasq:/etc/dnsmasq/' \
  -p 53:53 \
  dnsmasq
