#!/bin/bash

docker run -d \
  --env USER_ID=$(grep -P '^openhab' /etc/passwd | awk -F':' '{print $3}') \
  --env GROUP_ID=$(grep -P '^openhab' /etc/group | awk -F':' '{print $3}') \
  --restart=always \
  --name=openhab \
  --net=squid \
  --env CRYPTO_POLICY='limited' \
  --env EXTRA_JAVA_OPTS='-Dhttp.proxySet=true -Dhttp.proxyHost=squid -Dhttp.proxyPort=8080 -Dhttps.proxyHost=squid -Dhttps.proxyPort=8080 -Dhttp.nonProxyHosts=localhost' \
  --env http_proxy='http://nginx:8888' \
  --env https_proxy='https://nginx:8888' \
  -v '/etc/localtime:/etc/localtime:ro' \
  -v '/etc/timezone:/etc/timezone:ro' \
  -v 'openhab_conf:/openhab/conf/' \
  -v 'openhab_userdata:/openhab/userdata/' \
  -v 'openhab_addons:/openhab/addons/' \
  openhab/openhab
docker network connect nginx openhab
