#!/bin/bash

docker create \
  --env USER_ID=$(grep -P '^openhab' /etc/passwd | awk -F':' '{print $3}') \
  --env GROUP_ID=$(grep -P '^openhab' /etc/group | awk -F':' '{print $3}') \
  --restart=always \
  --name=openhab \
  --net=openhab_proxy \
  --env CRYPTO_POLICY='limited' \
  -v '/etc/localtime:/etc/localtime:ro' \
  -v '/etc/timezone:/etc/timezone:ro' \
  -v 'openhab_conf:/openhab/conf/' \
  -v 'openhab_userdata:/openhab/userdata/' \
  -v 'openhab_addons:/openhab/addons/' \
  openhab/openhab
cat > profile <<'EOF'
export OPENHAB_HTTP_ADDRESS=$(ip a | grep -A3 -P '^[[:digit:]]{1,10}: eth0' | grep inet | awk '{print $2}' | cut -d'/' -f1)
EOF
docker cp profile openhab:/etc/profile
docker start openhab
