#!/bin/bash




docker create \
  --env USER_ID=$(grep -P '^openhab' /etc/passwd | awk -F':' '{print $3}') \
  --env GROUP_ID=$(grep -P '^openhab' /etc/group | awk -F':' '{print $3}') \
  --restart=always \
  --name=openhab \
  --net=openhab_proxy \
  --ip=172.19.0.2 \
  --env CRYPTO_POLICY='limited' \
  -v '/etc/localtime:/etc/localtime:ro' \
  -v '/etc/timezone:/etc/timezone:ro' \
  -v 'openhab_conf:/openhab/conf/' \
  -v 'openhab_userdata:/openhab/userdata/' \
  -v 'openhab_addons:/openhab/addons/' \
  openhab/openhab
IP=$(docker inspect openhab | grep -oP 'IPAddress": "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | cut -d'"' -f3)
cat > profile <<EOF
export OPENHAB_HTTP_ADDRESS=${IP}
export http_proxy=http://nginx:8888
export https_proxy=https://nginx:8888
EOF
docker cp profile openhab:/etc/profile
rm -f profile
docker start openhab
