#!/bin/bash

docker pull debian
/usr/sbin/useradd -r -s /sbin/nologin voice
mkdir -p ./.build/voice/
cd ./.build/voice/
cat > Dockerfile <<'EOF'
FROM debian
RUN apt update -y
RUN apt install -y python3.7
RUN apt install -y python3-pip
RUN apt install -y libportaudio2
RUN pip3 install sounddevice
RUN pip3 install requests
RUN mkdir -p /opt/voice/
COPY ./exec/microphone.py /opt/voice/
CMD ["python3", "/opt/voice/microphone.py"]
EOF
docker build -t voice .
cd ../../
rm -rf ./.build/voice/
