#!/bin/bash

container_prep mycroft

cat > ./Dockerfile <<EOF
FROM debian
RUN apt update -y && apt upgrade -y
RUN apt install -y python3.7
RUN apt install -y python3-pip 
RUN apt install -y procps
RUN apt install -y git
RUN apt install -y python3-fann2
RUN pip3 install requests
RUN pip3 install inflection
RUN pip3 install pyaudio
RUN pip3 install psutil
RUN pip3 install padatious
RUN pip3 install py-dateutil
RUN pip3 install fasteners
RUN pip3 install websocket
RUN mkdir /root/build/
WORKDIR /root/build/
RUN git clone https://github.com/MycroftAI/mycroft-core.git
WORKDIR mycroft-core
RUN bash -x dev_setup.sh --allow-root
EOF

container_build mycroft
