#!/bin/bash

docker network create sphinx --internal
docker run -d \
  $(run_as sphinx) \
  --net=sphinx \
  --name=infra.sphinx \
  -v '/etc/localtime:/etc/localtime:ro' \
  -v '/etc/timezone:/etc/timezone:ro' \
  sphinx
