#!/bin/bash
source ./bin/activate

container_prep weather

cp -r ../../containers/99-weather/app ./

cat >Dockerfile <<'EOF'
FROM debian
RUN apt update -y; \
  apt upgrade -y; \
  apt install -y python3 \
  python3-pip \
  curl
COPY app /opt/app
WORKDIR /opt/app/
RUN pip3 install -r requirements.txt
CMD ["python3", "interface.py"]
EOF

container_build weather
