#!/bin/bash

source ./bin/activate

$(basic_container weather) \
  $(container_use_system_time) \
  --net=influxdb \
  -e API_KEY=$WEATHER_API_KEY \
  -e LAT="$LATITUDE" \
  -e LON="$LONGITUDE" \
  -e UNITS="$UNITS" \
  weather
docker start weather
