---
- name: create container
  docker_container:
    name: squid
    image: squid
    state: started
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - squid_conf:/etc/squid
      - squid_spool:/var/spool/squid
    ports:
      - 3128:3128/tcp
