#!/bin/bash

source ./bin/activate

container_prep logshipper

cat > Dockerfile <<'EOF'
FROM debian
RUN apt update -y
RUN apt upgrade -y
RUN apt install -y rsyslog
COPY 60-containers.conf /etc/rsyslog.d/60-containers.conf
RUN sed -i -e 's/module(load="imklog")/ /' /etc/rsyslog.conf
CMD ["/usr/sbin/rsyslogd", "-n"]
EOF

cat > 60-containers.conf <<EOF
module(load="imfile" PollingInterval="10")

template (name="LongTagForwardFormat" type="string"
string="<%PRI%>%TIMESTAMP:::date-rfc3339% %HOSTNAME% %syslogtag%%\$.suffix%%msg:::sp-if-no-1st-sp%%msg%")

ruleset(name="sendToLogserver") {
    action(type="omfwd" Target="monitor.deerlord.lan" Port="514" Template="LongTagForwardFormat")
}

input(type="imfile"
    File="/var/log/containers/*.log"
        Tag=""
        Ruleset="service_logs"
        addMetadata="on")

ruleset(name="service_logs") {
  set \$.suffix=re_extract(\$!metadata!filename, "(.*)/([^_/]*)", 0, 2, "unknown_container");
  call sendToLogserver
}
EOF

container_build logshipper
