#!/bin/bash

/usr/sbin/useradd -r -s /sbin/nologin voice
mkdir -p ./.build/voice/
cd ./.build/voice/
cp -r ../../containers/22-voice/app ./
cat > Dockerfile <<EOF
FROM debian
${APT_UPDATE}
RUN apt install -y python3.7
RUN apt install -y python3-pip
RUN apt install -y curl
RUN apt install -y swig
RUN apt install -y libpulse-dev
RUN apt install -y libasound2-dev
RUN apt install -y wget
RUN pip3 install pocketsphinx
RUN pip3 install SpeechRecognition
RUN pip3 install stanfordnlp
RUN python3 -c 'import stanfordnlp; stanfordnlp.download("en",force=True)'
COPY ./app /opt/app
EOF
docker build -t voice .
cd ../../
rm -rf ./.build/voice/
