#!/bin/bash

/usr/sbin/useradd -r -s /sbin/nologin voice
mkdir -p ./.build/voice/
cd ./.build/voice/
cp -r ../../containers/22-voice/app ./
cat > Dockerfile <<'EOF'
FROM debian
RUN apt update -y && apt upgrade -y && \
    apt install -y python3.7 \
    python3-pip \
    curl
RUN pip3 install pocketsphinx \
  SpeechRecognition \
  stanfordnlp \
RUN python3 -c 'import stanfordnlp; stanfordnlp.download("en",force=True)'
RUN apt install -y wget screen
RUN wget https://www.signalogic.com/melp/EngSamples/Orig/male.wav
COPY ./app /opt/app
EOF
docker build -t voice .
cd ../../
rm -rf ./.build/voice/
