#!/bin/bash

container_prep voice

cp -r ../../containers/22-voice/app ./
cat > Dockerfile <<EOF
FROM debian
RUN apt update -y && apt upgrade -y
RUN apt install -y python3.7
RUN apt install -y python3-pip
RUN apt install -y git
RUN apt install -y curl
RUN apt install -y swig
RUN apt install -y libpulse-dev
RUN apt install -y libasound2-dev
RUN apt install -y wget
RUN pip3 install pocketsphinx
RUN pip3 install SpeechRecognition
RUN pip3 install -e git+https://github.com/mycroftai/adapt#egg=adapt-parser
COPY ./app /opt/app
CMD ["python3", "/opt/app"]
EOF

container_build voice
