#!/bin/bash

$(basic_container voice) \
  --net=openhab \
  -v '/etc/localtime:/etc/localtime:ro' \
  -v '/etc/timezone:/etc/timezone:ro' \
  voice
http_ingress voice
sed -i '/^}/ d' /var/lib/docker/volumes/nginx/_data/conf.d/voice.conf
cat >> /var/lib/docker/volumes/nginx/_data/conf.d/voice.conf <<'EOF'
  # client cert stuff
  ssl_trusted_certificate /etc/ssl/command.crt;
  ssl_verify_client on;
}
EOF
