#!/bin/bash

container_prep ntpd

cat > Dockerfile <<'EOF'
FROM debian
RUN apt update -y
RUN apt upgrade -y
RUN apt install -y ntp
COPY ntp.conf /etc/ntp.conf
EXPOSE 123/udp
CMD ["/usr/sbin/ntpd", "-n"]
EOF
cat > ntp.conf <<EOF
listen on *
server time1.google.com
server time2.google.com
server time3.google.com
server time4.google.com
restrict default kod nomodify notrap nopeer noquery
restrict ${HOST_GATEWAY} mask ${HOST_SUBNET} modify notrap
server 127.127.1.0
fudge 127.127.1.0 stratum 10
driftfile /dev/shm/ntp.drift
EOF

container_build ntpd
