#!/bin/bash

/usr/sbin/useradd -r -s /sbin/nologin intent
mkdir -p ./.build/intent/
cd ./.build/intent/
cat > Dockerfile <<EOF
FROM debian
${APT_UPDATE}
RUN apt install -y git
RUN apt install -y python3.7
RUN apt install -y python3-pip
RUN git clone https://github.com/MycroftAI/mycroft-core.git 
EOF
docker build -t intent .
cd ../../
#rm -rf ./.build/intent/
