#!/bin/bash

/usr/sbin/useradd -r -s /sbin/nologin intent
mkdir -p ./.build/intent/
cd ./.build/intent/
cat > Dockerfile <<EOF
FROM debian
${APT_UPDATE}
RUN apt install -y git
RUN apt install -y python3.7
RUN apt install -y python3-pip
RUN apt install -y python3-fann2
RUN pip3 install requests
RUN pip3 install inflection
RUN pip3 install pyaudio
RUN pip3 install psutil
RUN pip3 install padatious
RUN pip3 install py-dateutil
RUN pip3 install fasteners
RUN pip3 install websocket
RUN pip3 install websocket-client
RUN pip3 install pyee
RUN pip3 install tornado
RUN pip3 install adapt-parser
RUN pip3 install msm
RUN pip3 install requests_futures
RUN pip3 install gtts
WORKDIR /root
RUN git clone https://github.com/MycroftAI/mycroft-core.git 
WORKDIR mycroft-core
RUN bash dev_setup.sh --allow-root
# use master? Y
# update automatically? N
# build mimic? Y (but not now)
# add helper functions? Y
# code style? Y
EOF
docker build -t intent .
cd ../../
#rm -rf ./.build/intent/
