---
- name: deploy container
  docker_container:
    name: dnsmasq
    image: dnsmasq
    state: started
    volumes:
      - dnsmasq:/etc/dnsmasq
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 67:67/udp
