#!/bin/bash

/usr/sbin/useradd -r -s /sbin/nologin dnsmasq
docker volume create dnsmasq
mkdir ./dnsmasq/
cd ./dnsmasq/
cat > Dockerfile <<'EOF'
FROM debian
RUN apt update -y
RUN apt upgrade -y
RUN apt install -y wget
RUN apt install -y dnsmasq dnsmasq-utils
RUN mkdir -p /etc/dnsmasq/
RUN echo 'conf-file=/etc/dnsmasq/conf' > /etc/dnsmasq.conf
EXPOSE 53/udp
EXPOSE 53/tcp
EXPOSE 67/udp
CMD ["/usr/sbin/dnsmasq", "-k", "--log-facility=/var/log/dnsmasq"]
EOF
cat > /var/lib/docker/volumes/dnsmasq/_data/local_hosts <<EOF
${HOST_IP} ${HOST_NAME} ${HOST_NAME}.${HOST_DOMAIN}
${HOST_GATEWAY} router router.${HOST_DOMAIN}
EOF
add_static_lease ${HOST_MAC} ${HOST_IP}
cat > /var/lib/docker/volumes/dnsmasq/_data/conf <<EOF
user=root
domain-needed
bogus-priv
no-resolv
no-poll
local=/HOST_NAME/
addn-hosts=/etc/dnsmasq/local_hosts
addn-hosts=/etc/dnsmasq/ad_domains
conf-file=/etc/dnsmasq/static
dhcp-leasefile=/etc/dnsmasq/leases
server=/${HOST_NAME}/
server=8.8.8.8
server=8.8.4.4
no-hosts
expand-hosts
domain=${HOST_DOMAIN}
dhcp-range=${DHCP_START},${DHCP_END},${DHCP_TIME}
dhcp-option=option:router,${HOST_GATEWAY}
#dhcp-option=option:ntp-server,/${NTP_SERVER}/
#dhcp-range=eth,${DHCP_ETH_START},${DHCP_ETH_END},${DHCP_ETH_TIME}
#dhcp-range=wifi,${DHCP_WIFI_START},${DHCP_WIFI_END},${DHCP_WIFI_TIME}
log-queries
log-dhcp
EOF
#sed -i \
#  -e "s HOST_IP ${HOST_IP} g" \
#  -e "s HOST_NAME ${HOST_NAME} g" \
#  -e "s HOST_DOMAIN ${HOST_DOMAIN} g" \
#  -e "s HOST_GATEWAY ${HOST_GATEWAY} g" \
#  /var/lib/docker/volumes/dnsmasq/_data/hosts
#sed -i \
#  -e "s HOST_NAME ${HOST_NAME} g" \
#  -e "s HOST_DOMAIN ${HOST_DOMAIN} g" \
#  -e "s HOST_IP ${HOST_IP} g" \
#  -e "s HOST_GATEWAY ${HOST_GATEWAY} g" \
#  -e "s DHCP_START ${DHCP_START} g" \
#  -e "s DHCP_END ${DHCP_END} g" \
#  -e "s DHCP_TIME ${DHCP_TIME} g" \
#  -e "s NTP_SERVER ${NTP_SERVER} g" \
#  /var/lib/docker/volumes/dnsmasq/_data/conf
docker build -t dnsmasq .
cd ..
rm -rf ./dnsmasq/
update_ad_domains
chown -R dnsmasq /var/lib/docker/volumes/dnsmasq/_data/

