#!/bin/bash

$(basic_container dnsmasq) \
  --cap-add=NET_ADMIN \
  -v 'dnsmasq:/etc/dnsmasq/' \
  -p 53:53/tcp \
  -p 53:53/udp \
  -p 67:67/udp \
  --dns=${DNS_ONE} \
  --dns=${DNS_TWO} \
  dnsmasq
public_service dns
