#!/bin/bash

docker pull nginx
/usr/sbin/useradd -r -s /sbin/nologin nginx
docker volume create nginx
docker volume create ssl
docker run -d \
  $(run_as nginx) \
  --restart=always \
  --name=nginx \
  --net=host \
  -v '/etc/localtime:/etc/localtime:ro' \
  -v '/etc/timezone:/etc/timezone:ro' \
  -v 'nginx:/etc/nginx/' \
  nginx
sleep 10
docker stop nginx
docker rm nginx
rm /var/lib/docker/volumes/nginx/_data/conf.d/default.conf
mkdir -p /var/lib/docker/volumes/ssl/_data/clients/
mkdir -p /var/lib/docker/volumes/ssl/_data/revoked/
touch /var/lib/docker/volumes/ssl/_data/clients.crt
touch /var/lib/docker/volumes/ssl/_data/revoked.crt
cat > /var/lib/docker/volumes/nginx/_data/conf.d/force_https.conf <<'EOF'
server {
  listen 80 default_server;
  server_name _;
  return 301 https://$host$request_uri;
}
server {
  listen 443 ssl;
  server_name *.HOST_DOMAIN;
  ssl_certificate /etc/ssl/nginx.crt;
  ssl_certificate_key /etc/ssl/nginx.key;
  ssl_protocols TLSv1.3;
}
EOF
cat > /var/lib/docker/volumes/nginx/_data/conf.d/items.conf <<'EOF'
server {
  listen 443 ssl;
  server_name control.deerlord.lan;
  ssl_certificate /etc/ssl/nginx.crt;
  ssl_certificate_key /etc/ssl/nginx.key;
  ssl_protocols TLSv1.3;
  ssl_client_certificate /etc/ssl/clients.crt;
  ssl_crl /etc/ssl/revoked.crt;
  ssl_verify_client on;
}
EOF
> /var/lib/docker/volumes/nginx/_data/conf.d/items.conf
cat > /var/lib/docker/volumes/nginx/_data/conf.d/blackhole.conf <<'EOF'
server {
  listen 443 ssl default_server;
  ssl_certificate /etc/ssl/nginx.crt;
  ssl_certificate_key /etc/ssl/nginx.key;
  ssl_protocols TLSv1.3;
  return 444;
}
EOF
sed -i \
  -e "s HOST_DOMAIN ${HOST_DOMAIN} g" \
  /var/lib/docker/volumes/nginx/_data/conf.d/force_https.conf
openssl req -newkey rsa:8192 -nodes \
  -keyout /var/lib/docker/volumes/ssl/_data/nginx.key \
  -x509 -days 3650 \
  -out /var/lib/docker/volumes/ssl/_data/nginx.crt \
  -subj "/C=${COUNTRY}/ST=${STATE}/L=${LOCALITY}/O=${ORGANIZATION}/OU=${ORGANIZATIONALUNIT}/CN=${COMMONNAME}/emailAddress=${EMAIL}"
chown -R nginx /var/lib/docker/volumes/nginx/_data/
