#!/bin/bash
source ./bin/activate

setup_prep nameresolution

docker volume create dnsmasq

cat > ${VOLUMES}/dnsmasq/_data/local_hosts <<EOF
${HOST_IP} ${HOST_NAME} ${HOST_NAME}.${HOST_DOMAIN}
${HOST_GATEWAY} router router.${HOST_DOMAIN}
EOF

touch ${VOLUMES}/dnsmasq/_data/static
add_static_lease ${HOST_MAC} ${HOST_IP}
add_static_lease ${GATEWAY_MAC} ${HOST_GATEWAY}
cat > ${VOLUMES}/dnsmasq/_data/conf <<EOF
user=root
domain-needed
bogus-priv
no-resolv
proxy-dnssec
server=127.0.0.1#853
no-poll
domain=${HOST_DOMAIN}
expand-hosts
local=/${HOST_DOMAIN}/
addn-hosts=/etc/dnsmasq/local_hosts
addn-hosts=/etc/dnsmasq/ad_domains
conf-file=/etc/dnsmasq/static
dhcp-leasefile=/etc/dnsmasq/leases
dhcp-option=6,${HOST_GATEWAY}
no-hosts
dhcp-range=${DHCP_START},${DHCP_END},${DHCP_TIME}
dhcp-option=option:router,${HOST_GATEWAY}
dhcp-option=option:ntp-server,${HOST_IP}
#dhcp-range=eth,${DHCP_ETH_START},${DHCP_ETH_END},${DHCP_ETH_TIME}
#dhcp-range=wifi,${DHCP_WIFI_START},${DHCP_WIFI_END},${DHCP_WIFI_TIME}
dhcp-lease-max=25
log-queries
log-dhcp
EOF

sed -i '1s|^|load_module "modules/ngx_stream_js_module.so";\n|' ${VOLUMES}/nginx/_data/nginx.conf

cat > ${VOLUMES}/nginx/_data/conf.d/doh_gateway.stream <<'EOF'
stream {
  js_include /etc/nginx/njs.d/nginx_stream.js;
  upstream dns {
    zone dns 64k;
    server nameresolution:53;
  }
  server {
    listen 8053 ssl;
    js_filter dns_filter_doh_request;
    ssl_certificate /etc/nginx/ssl/certs/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/private/nginx.key;
    proxy_pass dns;
  }
}
EOF

update_ad_domains
set_volume_ownership nameresolution dnsmasq
