---
- name: open firewall
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 443/tcp
- name: setup image
  docker_image:
    name: nginx
    path: roles/nginx/docker/
    state: build
- name: create configuration volume
  docker_volume:
    name: nginx
    state: present
- name: create ssl volume
  docker_volume:
    name: ssl
    state: present
- name: configuration
  template:
    src: roles/nginx/docker/conf/force_https.conf.j2
    dest: /var/lib/docker/volumes/nginx/_data/force_https.conf
- name: create private key
  openssl_privatekey:
    path: /var/lib/docker/volumes/ssl/_data/nginx.key
- name: create csr
  openssl_csr:
    path: /var/lib/docker/volumes/ssl/_data/nginx.csr
    privatekey_path: /var/lib/docker/volumes/ssl/_data/nginx.key
    force: yes
    common_name: "*.{{ HOST_DOMAIN }}"
- name: create ssl
  openssl_certificate:
    path: /var/lib/docker/volumes/ssl/_data/nginx.crt
    privatekey_path: /var/lib/docker/volumes/ssl/_data/nginx.key
    csr_path: /var/lib/docker/volumes/ssl/_data/nginx.csr
    provider: selfsigned
- name: create container
  docker_container:
    name: nginx
    image: nginx
    state: started
    volumes:
      - nginx:/etc/nginx/conf.d
      - ssl:/etc/ssl
    ports:
      - 443:443/tcp

