---
- hosts: localhost
  remote_user: root
  become: yes
  become_method: sudo
  vars_files:
    - group_vars/all
  tasks:
    - name: install docker
      package:
        name: docker
        state: present
    - name: remove python docker-py
      pip:
        name: docker-py
        state: absent
    - name: install python docker
      pip:
        name: docker
        state: present
    - name: 
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - 80/tcp
        - 123/tcp
        - 443/tcp
    - include_tasks: dnsmasq.yml
