---
- name: create configuration volume
  docker_volume:
    name: openhab_conf
    state: present
- name: create userdata volume
  docker_volume:
    name: openhab_userdata
    state: present
- name: create addons volume
  docker_volume:
     name: openhab_addons
     state: present
- name: make services folder
  file:
    path: /var/lib/docker/volumes/openhab_conf/_data/services
    state: directory
- name: addons configuration
  template:
    src: roles/openhab/docker/conf/addons.cfg.j2
    dest: /var/lib/docker/volumes/openhab_conf/_data/services/addons.cfg
- name: sqlite configuration
  template:
    src: roles/openhab/docker/conf/jdbc.cfg.j2
    dest: /var/lib/docker/volumes/openhab_conf/_data/services/jdbc.cfg



     #cat >> ${VOLUMES}/openhab_conf/_data/services/addons.cfg <<'EOF'
     #persistence = 'jdbc'
     #EOF
     #touch ${VOLUMES}/openhab_userdata/_data/sqlite.db
     #cat > ${VOLUMES}/openhab_conf/_data/services/jdbc.cfg <<'EOF'
     #url=jdbc:sqlite:/openhab/userdata/sqlite.db
     #EOF

