#!/bin/bash
source ./bin/activate

setup_prep nginx

docker pull nginx
docker volume create nginx
docker run -d \
  $(run_as nginx) \
  --restart=always \
  --name=nginx \
  --net=host \
  $(container_use_system_time) \
  -v 'nginx:/etc/nginx/' \
  nginx
sleep 10
docker stop nginx
docker rm nginx
mkdir -p ${VOLUMES}/nginx/_data/ssl/private/
mkdir -p ${VOLUMES}/nginx/_data/ssl/certs/
mkdir -p ${VOLUMES}/nginx/_data/ssl/clients/
mkdir -p ${VOLUMES}/nginx/_data/ssl/revoked/
touch ${VOLUMES}/nginx/_data/ssl/clients.crt
touch ${VOLUMES}/nginx/_data/ssl/revoked.crt

cat > ${VOLUMES}/nginx/_data/conf.d/force_https.conf <<'EOF'
server {
  listen 80 default_server;
  server_name *.HOST_DOMAIN;
  return 301 https://$host$request_uri;
}
server {
  listen 443 ssl http2;
  server_name _;
  ssl_certificate /etc/nginx/ssl/certs/nginx.crt;
  ssl_certificate_key /etc/nginx/ssl/private/nginx.key;
  ssl_protocols TLSv1.3;
}
EOF
# remove final bracket
sed -i -e '$d' ${VOLUMES}/nginx/_data/nginx.conf 
cat >> ${VOLUMES}/nginx/_data/nginx.conf <<'EOF'
    server_names_hash_bucket_size 128;
}
include /etc/nginx/coonf.d/*.stream;
EOF

git clone https://github.com/TuxInvader/nginx-dns.git
cd nginx-dns
cp -rv njs.d ${VOLUMES}/nginx/_data/

sed -i \
  -e "s HOST_DOMAIN ${HOST_DOMAIN} g" \
  ${VOLUMES}/nginx/_data/conf.d/force_https.conf


#$ TODO: replace with letsencrypt
openssl req -newkey rsa:8192 -nodes \
  -keyout ${VOLUMES}/nginx/_data/ssl/private/nginx.key \
  -x509 -days 3650 \
  -out ${VOLUMES}/nginx/_data/ssl/certs/nginx.crt \
  -subj "/C=${COUNTRY}/ST=${STATE}/L=${LOCALITY}/O=${ORGANIZATION}/OU=${ORGANIZATIONALUNIT}/CN=${COMMONNAME}/emailAddress=${EMAIL}"

set_volume_ownership nginx
chown -R root ${VOLUMES}/nginx/_data/ssl/private
chmod -R g-wx ${VOLUMES}/nginx/_data/ssl/private

